In [18]:
import numpy as np
import cv2 as cv
import glob

In [19]:
chessboard_size = (14,10)

In [20]:
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

In [21]:
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((chessboard_size[0]*chessboard_size[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1,2)

In [22]:
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.

In [23]:
images = glob.glob('*.JPG')

In [24]:
for image in images:
    img = cv.imread(image)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, chessboard_size, None)
    
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        
        corners2 = cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
        
        # Draw and display the corners
        cv.drawChessboardCorners(img, chessboard_size, corners2, ret)
        scale_percent = 25  # Уменьшаем изображение до 50% от оригинального размера
        width = int(img.shape[1] * scale_percent / 100)
        height = int(img.shape[0] * scale_percent / 100)
        dim = (width, height)
        resized_img = cv.resize(img, dim, interpolation=cv.INTER_AREA)
        cv.imshow('img', resized_img)
        cv.waitKey(500)

cv.destroyAllWindows()

In [25]:
# Калибровка
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

print(f"Camera calibrated:\n{ret}\n")
print(f"Camera matrix (внутренняя калибровка):\n{mtx}\n")
print(f"Distortion parameters:\n{dist}\n")
print(f"Rotation vectors (внешняя калибровка):\n{rvecs}\n")
print(f"Translation vectors (внешняя калибровка):\n{tvecs}\n")

Camera calibrated:
2.0045775596758424

Camera matrix (внутренняя калибровка):
[[6.05304386e+03 0.00000000e+00 2.54106629e+03]
 [0.00000000e+00 6.03790771e+03 1.30293217e+03]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]

Distortion parameters:
[[-1.75617496e-01  3.62500911e+00  3.27014250e-03  3.28190397e-03
  -2.11790265e+01]]

Rotation vectors (внешняя калибровка):
(array([[ 0.45590314],
       [-0.33471187],
       [-0.07278109]]), array([[ 0.45060017],
       [-0.2504773 ],
       [-0.0211829 ]]), array([[ 0.45231412],
       [-0.08096209],
       [ 0.01110823]]), array([[0.40956276],
       [0.09488636],
       [0.02728659]]), array([[0.42292284],
       [0.09803041],
       [0.01790061]]), array([[0.41234971],
       [0.22872319],
       [0.07403409]]), array([[0.38685734],
       [0.23959846],
       [0.06260513]]), array([[0.38663205],
       [0.33821258],
       [0.10402405]]), array([[0.37301525],
       [0.28350842],
       [0.08806543]]), array([[ 0.50062551],
       [-0